version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:15-alpine3.18
    container_name: db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password